### ISSUE TITLE
Can I request more fields from Graph API?

### ISSUE THREAD

**Issue by KKKKKyle** [fbsamples/original-coast-clothing#33]
#### When try to request more fields from GraphAPI, the request failed.
I am working on a project by using this project as an example. Thanks so much for building all these. I was trying to get more fields from GraphAPI, so that I may connect users to each other by sending out a link of others' Facebook pages.

#### To Reproduce
1. Go to 'graph-api.js'
2. Add more fields listed on [Graph API User official website](https://developers.facebook.com/docs/graph-api/reference/user/) on line 134, under function callUserProfileAPI(senderPsid). 
3. Deploy and go to Heroku log console.
4. See error: (DONATE_MORE is the paylaod I defined.)
```
2019-08-22T17:54:17.350841+00:00 app[web.1]: Profile already exists PSID: 2343351982428387 with locale: en_US
2019-08-22T17:54:17.350871+00:00 app[web.1]: Received Payload: DONATE_MORE for 2343351982428387
2019-08-22T17:54:17.414932+00:00 app[web.1]: FBA event 'DONATE_MORE'
2019-08-22T17:54:17.436829+00:00 app[web.1]: Fetch failed: Error: 400
2019-08-22T17:54:17.436833+00:00 app[web.1]:     at Request.<anonymous> (/app/services/graph-api.js:143:20)
2019-08-22T17:54:17.436835+00:00 app[web.1]:     at Request.emit (events.js:209:13)
2019-08-22T17:54:17.436838+00:00 app[web.1]:     at Request.onRequestResponse (/app/node_modules/request/request.js:1066:10)
2019-08-22T17:54:17.436840+00:00 app[web.1]:     at ClientRequest.emit (events.js:209:13)
2019-08-22T17:54:17.436842+00:00 app[web.1]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:582:27)
2019-08-22T17:54:17.436844+00:00 app[web.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
2019-08-22T17:54:17.436846+00:00 app[web.1]:     at TLSSocket.socketOnData (_http_client.js:456:22)
2019-08-22T17:54:17.436849+00:00 app[web.1]:     at TLSSocket.emit (events.js:209:13)
2019-08-22T17:54:17.436850+00:00 app[web.1]:     at addChunk (_stream_readable.js:305:12)
2019-08-22T17:54:17.436852+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:286:11)
```

**Comment by jorgeluiso** [comment]
This is by design. Since Messenger deals with Page Scoped IDs the only profile available is this one:

https://developers.facebook.com/docs/messenger-platform/identity/user-profile/

The following link refers to ASIDs app scoped user ids.
https://developers.facebook.com/docs/graph-api/reference/user/
