### ISSUE TITLE
Short description of the issue

### ISSUE THREAD

**Issue by hongsolo9** [fbsamples/original-coast-clothing#60]
#### Describe the bug
Reproducible error - Unable to proceed with FB messenger tutorial. HTTP response says 

> ERROR - Need a proper API_URL in the .env file

Which I already have one in the .env file

Nodejs command line shows error diarrhoea (See below for error messages.)

#### To Reproduce
1. Setup nodejs (v12.17.0)
2. git clone https://github.com/fbsamples/original-coast-clothing.git; cd original-coast-clothing
3. yarn install
4. Complete .env as required
`API_URL="http://XXXXXXXXXXX.ngrok.io"`
5. node app.js
6. Set up ngrok as local http tunnel
7. Send a GET request to http://localhost:3000/profile?mode=all&verify_token=AAAAAA

#### Expected behavior
Not sure because all I've got are error messages on the http response and on the nodejs console.

#### Error message
HTTP Response (on web browser)

> ERROR - Need a proper API_URL in the .env file

Nodejs console
```
Setting Messenger Profile for app 13672067XXXXXXXX
Fetching personas for app 13672067XXXXXXXX
Enable Built-in NLP for Page 1061562XXXXXXXX
{ whitelisted_domains: [ 'http://XXXXXXXXXXX.ngrok.io', undefined ] }
Setting Messenger Profile for app 13672067XXXXXXXX
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:629:17)
    at ServerResponse.write (_http_outgoing.js:621:15)
    at /Users/kingchangco/Projects/original-coast-clothing/app.js:180:13
    at Layer.handle [as handle_request] (/Users/kingchangco/Projects/original-coast-clothing/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kingchangco/Projects/original-coast-clothing/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/kingchangco/Projects/original-coast-clothing/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kingchangco/Projects/original-coast-clothing/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kingchangco/Projects/original-coast-clothing/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/kingchangco/Projects/original-coast-clothing/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kingchangco/Projects/original-coast-clothing/node_modules/express/lib/router/index.js:275:10)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:684:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by jorgeluiso** [comment]
I think is because the API URL needs to be HTTPS I noticed that on the repro steps you put HTTP. Can you verify if this is the issue?

**Comment by rubycalling** [comment]
This issue hasn't been updated in more than three months.

**Comment by krehy** [comment]
Hey, the same problem..
https://github.com/fbsamples/original-coast-clothing/issues/90
